<?php


namespace App\Providers;


use Illuminate\Support\ServiceProvider;

class BackendServiceProvider extends ServiceProvider
{
    public function register()
    {
        //parent::register(); // TODO: Change the autogenerated stub
        $this->app->bind(
            'App\Repositories\RepositoryInterfaces\ServiceRepositoryInterface',
            'App\Repositories\DBRepositories\ServiceDBRepository'

        );
    }

}
